import React, { useEffect } from "react";

const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="max-w-[1200px] mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-8">Privacy Policy for Vikram Aura Hospital</h1>
      <p className="text-sm text-gray-600 mb-8">Last Updated: June 2025<br />Version: 1</p>

      <div className="prose max-w-none">
        <p className="mb-6">
          Vikram Aura Private Limited, having its registered address at 62, Mother Teresa Rd Xavier Layout, Victoria Layout, Richmond Town, Bangalore, Karnataka, India, 560025 ("Vikram Aura," "we," "us," or "our"), is committed to protecting the privacy and confidentiality of your personal data and ensure that we take reasonable care and protection of the information we receive from you.
        </p>

        <p className="mb-6">
          This Privacy Policy is an electronic record in terms of Indian Contract Act 1872; the Information Technology Act 2000, the rules made thereunder; and the amended provisions pertaining to the electronic records in various other statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signature.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Information we Collect</h2>
        <p className="mb-4">1.1. We may collect certain information about you when you visit our website and or through your physical interaction with our staff to provide you our healthcare services. We collect this information only with your consent where required and ensure it is used solely for the purposes outlined in this Privacy Policy.</p>
        <p className="mb-4">1.2. The type of information which we may collect is your name, address, age, sex, medical report(s), medical history, physical, physiological and mental health condition, financial information like bank account or credit card or debit card or other payment instrument details, or any other information as required to provide you desired services.</p>
        <p className="mb-6">1.3. Information we acquire or generate once availing services and during your association with us:</p>
        <ul className="list-disc pl-8 mb-6">
          <li>Appointment Date and Time</li>
          <li>Treating Doctor's name</li>
          <li>Appointment Type</li>
          <li>Appointment ID</li>
          <li>Vikram Aura ID</li>
          <li>Martial Status</li>
          <li>First Registration Date</li>
          <li>Insurance (If any)</li>
          <li>Government ID</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">2. Purpose of Data Processing</h2>
        <p className="mb-4">We process your personal data only for specified, lawful purposes. These include:</p>
        <ul className="list-disc pl-8 mb-6">
          <li>Providing healthcare services, including diagnosis, treatment, and follow-up care</li>
          <li>Respond to your enquiries and fulfil your requests</li>
          <li>Managing appointments and patient records</li>
          <li>Processing billing, insurance claims, or reimbursements</li>
          <li>Communicating health updates, appointment reminders, or hospital services</li>
          <li>Ensuring compliance with legal and regulatory obligations</li>
          <li>Improving healthcare services through quality assurance and anonymized analytics</li>
          <li>Conducting medical research, only with your explicit consent or using anonymized data</li>
          <li>Enhancing user experience on our digital platforms</li>
          <li>Sending marketing communications with respect to our services</li>
          <li>For sale or transfer of such research, statistical, or intelligence data in an aggregated or non-personally identifiable form to our partners</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">3. Disclosure of Personal Data</h2>
        <p className="mb-4">We may disclose your personal data only in the following circumstances:</p>
        <ul className="list-disc pl-8 mb-6">
          <li>Healthcare Providers: To doctors, nurses, or specialists involved in your care, with your consent or for treatment purposes</li>
          <li>Third-Party Processors: To authorized service providers (e.g., laboratories), bound by confidentiality and data protection agreements</li>
          <li>Insurance Providers: For processing claims, with your consent</li>
          <li>Legal Authorities: When required by law (e.g., for infectious disease reporting or court orders)</li>
          <li>With Consent: To family members, caregivers, or other hospitals as per your instructions</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">4. Data Security</h2>
        <p className="mb-6">
          While we will endeavour to take all reasonable and appropriate steps to keep secure any information that We hold about You and prevent unauthorized access, you acknowledge that the internet is not 100% secure and that We cannot provide any absolute assurance regarding the security of Your Personal Information.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">5. Your Rights</h2>
        <p className="mb-4">You have the following rights regarding your personal information:</p>
        <ul className="list-disc pl-8 mb-6">
          <li>Right to Access: Request a summary of your data and how we use it</li>
          <li>Right to Correction: Ask us to fix incorrect or incomplete data</li>
          <li>Right to Withdraw Consent: Stop us from using your data, where possible, subject to legal requirements</li>
          <li>Right to Grievance Redressal: Raise concerns about how we handle your data with our Grievance Redressal Officer</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">6. Data Retention</h2>
        <p className="mb-6">
          We keep your personal information only as long as needed for the purposes listed or as required by law. Medical records are kept according to applicable healthcare rules. Data we no longer need is securely deleted or anonymized.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">7. Cookies and Tracking Technologies</h2>
        <p className="mb-6">
          Our website use cookies to improve functionality and understand usage patterns. We ask for your permission before using cookies that collect personal information. You can manage cookie settings through your browser, though disabling cookies may affect how our platforms work.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">8. Third-Party Links</h2>
        <p className="mb-6">
          Our website or services may include references to third parties or links to their websites. We are not responsible for their privacy practices. Please review their policies before sharing information with them.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">9. Updates to this Privacy Policy</h2>
        <p className="mb-6">
          This Privacy Policy may be updated periodically. When we make changes, we will publish the updated version on the website or notify you via other channels.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">10. Children's Privacy</h2>
        <p className="mb-6">
          We are committed to protecting the privacy of children under 18. We do not knowingly collect personal information from minors without verified consent from a parent or legal guardian.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">11. Data Protection Officer and Grievance Redressal</h2>
        <p className="mb-4">For questions, requests, or complaints about your data, contact our Grievance Redressal Officer:</p>
        <div className="pl-8 mb-8">
          <p className="font-semibold">Vikram Aura Hospital</p>
          <p>Grievance Redressal Officer: HIMESH JOSHI</p>
          <p>Address: Bangalore, Karnataka - 560066</p>
          <p>Email: himesh@vikramaura.com</p>
          <p>Phone: +91 81979 68957</p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy; 