import { useEffect } from "react";

const TermsOfService = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="max-w-[1200px] mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <p className="text-sm text-gray-600 mb-8">Last Updated: [●]<br />Version: 1</p>

      <div className="prose max-w-none">
        <p className="mb-6">
          These Terms and Conditions ("Terms") govern your access to and use of the website accessible at https://vikramaurahospitals.com, and all software, products, services, content, and features made available through it (collectively, the "Website"), except where we expressly state that separate terms apply.
        </p>

        <p className="mb-6">
          The Website is owned and operated by Vikram Aura Private Limited, a company incorporated in India under provisions of the Companies Act, 2013, having its registered office at 62, Mother Teresa Rd Xavier Layout, Victoria Layout, Richmond Town, Richmond Town, Bangalore, Bangalore North, Karnataka, India, 560025 (hereinafter referred to as "Hospital", "Vikram Aura", "we", "us" or "our"). These Terms also include our Privacy Policy ("Privacy Policy") available at <a href="/privacy-policy" className="text-orange-400 hover:text-orange-600">Privacy Policy</a>, and any additional policies, guidelines, notices, disclaimers, or terms made available or published by us from time to time, each of which is incorporated into and forms a part of these Terms by reference.
        </p>

        <p className="mb-6">
          For the purposes of these Terms, references to "you", "your" or "user" shall mean any individual or entity accessing or using the Website. Please read these Terms carefully before using the Website. By accessing or using any part of the Website, you confirm that you have read, understood, and agreed to be bound by these Terms, including any updates made from time to time, and that you meet the legal eligibility requirements set out herein.
        </p>

        <p className="mb-6">
          You represent and warrant that you have full legal capacity and authority to enter into and be bound by these Terms. If you are accessing or using the Website on behalf of another person, organisation, or legal entity, you represent and warrant that you are duly authorised to bind such person or entity to these Terms.
        </p>

        <p className="mb-6">
          If you do not agree to these Terms, our Privacy Policy, or any other rules or restrictions made available to you while using the Website, you are not permitted to use or access the Website and must immediately cease such use.
        </p>

        <p className="mb-8">
          These Terms constitute an electronic record under the Indian Contract Act, 1872; the Information Technology Act, 2000; and the applicable rules made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signature.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">User Responsibilities and Conduct</h2>
        
        <h3 className="text-xl font-semibold mt-6 mb-3">General Obligations</h3>
        <p className="mb-4">
          You agree to use the Website in a lawful, responsible, and respectful manner in compliance with these Terms and applicable laws. You shall not use the Website for any purpose that is prohibited by these Terms, violates any applicable law, regulation, or contractual obligation, or infringes upon the rights of others.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-3">Accuracy and Content</h3>
        <p className="mb-4">
          You are solely responsible for the accuracy, completeness, and legality of any information or data you provide on the Website. You represent and warrant that all information you submit:
        </p>
        <ul className="list-disc pl-8 mb-6">
          <li>Is truthful, accurate, and not misleading;</li>
          <li>Does not infringe upon the intellectual property, privacy, or other legal rights of any third party; and</li>
          <li>Complies with all applicable laws.</li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-3">Prohibited Activities</h3>
        <p className="mb-4">
          You agree not to engage in any conduct that disrupts, damages, or exploits the Website or its underlying systems. Specifically, you shall not:
        </p>
        <ul className="list-disc pl-8 mb-6">
          <li>Attempt to gain unauthorized access to the Website, its servers, databases, or networks;</li>
          <li>Introduce or transmit malicious code such as viruses or malware;</li>
          <li>Engage in data scraping, reverse engineering, or similar activities;</li>
          <li>Use automated tools or bots to interact with the Website without our written permission; or</li>
          <li>Attempt to disrupt the Website's functionality, including via denial-of-service attacks.</li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-3">Misrepresentation and Fraud</h3>
        <p className="mb-6">
          You shall not impersonate any person or entity, misrepresent your identity, or attempt to deceive or defraud Hospital or other users. Submitting false information or engaging in fraudulent activity may result in termination of your access to the Website and legal consequences.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Disclaimer</h2>
        <p className="mb-4">
          The Website and any associated services are provided "as is" and "as available," without warranties of any kind, whether express or implied. To the fullest extent permitted by law, Hospital disclaims all warranties including but not limited to:
        </p>
        <ul className="list-disc pl-8 mb-6">
          <li>Accuracy, completeness, or reliability of the Website content;</li>
          <li>Fitness for a particular purpose or non-infringement;</li>
          <li>Uninterrupted or error-free access; and</li>
          <li>Freedom from harmful code or technical issues.</li>
        </ul>

        <p className="mb-4">
          The Website may include links to or integrations with third-party services. Hospital does not guarantee the quality, safety, or performance of such services and disclaims all liability arising from their use. Your interaction with third-party services is governed by their respective terms.
        </p>

        <p className="mb-4">
          You are solely responsible for your use of the Website and any decisions or actions taken based on the information available through it. Hospital is not liable for any harm or loss arising from reliance on Website content, except where such liability results solely from Hospital's gross negligence or wilful misconduct as determined by a court of competent jurisdiction.
        </p>

        <p className="mb-4">
          To the maximum extent permitted by law, Hospital shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to:
        </p>
        <ul className="list-disc pl-8 mb-6">
          <li>Loss of profits, revenue, savings, or business opportunities;</li>
          <li>Loss of data or reputation;</li>
          <li>Personal injury or property damage; or</li>
          <li>Emotional distress or inconvenience;</li>
        </ul>
        <p className="mb-4">arising from your use of the Website, even if Hospital has been advised of the possibility of such damages.</p>

        <p className="mb-4">
          Hospital is not liable for failures or delays caused by events beyond its reasonable control, including but not limited to power outages, network failures, natural disasters, or government actions.
        </p>

        <p className="mb-6">
          We make no representations or warranties regarding the compatibility of the Website with your specific hardware, software, or network environment; and the ability of the Website to integrate seamlessly with third-party systems or services. You are solely responsible for ensuring your equipment and connectivity meet the minimum requirements specified on the Website.
        </p>

        <p className="mb-8">
          Nothing in this Disclaimer shall exclude or limit liability that cannot be disclaimed under applicable Indian law, such as liability for fraud, misrepresentation, or death or personal injury caused by our negligence, as provided under the Consumer Protection Act, 2019, or other relevant statutes. Where our liability cannot be excluded, it shall be limited to the maximum extent permitted by law. You agree that your decision to use the Website is voluntary and that you assume full responsibility for the consequences of such use, except as expressly provided herein.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Intellectual Property Rights</h2>
        <p className="mb-4">
          All rights, title, and interest in the Website, including software, databases, content, designs, logos, trademarks, and associated documentation, are the exclusive property of Hospital or its licensors. Nothing in these Terms grants you ownership or any rights in our intellectual property except for the limited usage rights expressly provided herein.
        </p>

        <p className="mb-4">
          All content and materials available on this Website, including but not limited to text, images, graphics, logos, audio, video, and downloadable files, are the intellectual property of the Hospital or the original creator, and are protected by applicable copyright laws of India. Unless expressly stated otherwise, no content on this Website is part of the public domain.
        </p>

        <p className="mb-4">
          You may download, copy, reproduce, redistribute, republish, display, or transmit specific materials from the Website only where Hospital has expressly granted prior written permission for such use, and only with respect to the materials so designated.
        </p>

        <p className="mb-4">
          Hospital makes no representation or warranty that your use of any materials on this Website will not infringe upon the rights of third parties. You are solely responsible for ensuring that any such use complies with applicable intellectual property laws.
        </p>

        <p className="mb-4">
          Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable right to access and use the Website for personal, non-commercial purposes. You shall not copy, modify, distribute, reverse engineer, or create derivative works from any part of the Website without prior written consent.
        </p>

        <p className="mb-4">
          You shall not use the Website in any way that infringes on the intellectual property rights of Hospital or any third party. This includes using our logos, marks, or branding without prior permission.
        </p>

        <p className="mb-6">
          We reserve the right to take legal action to enforce our intellectual property rights, including suspension of your access, monetary claims, or injunctive relief.
        </p>

        <p className="mb-8">
          Your use of the Website does not grant any implied rights or licenses beyond those expressly provided. Unauthorized use may result in civil or criminal liability.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Indemnity</h2>
        <p className="mb-4">
          You agree to indemnify, defend, and hold harmless the Company, its parent entities, subsidiaries, affiliates, directors, officers, employees, contractors, agents, licensors, representatives, and assigns (collectively, the "Indemnified Parties") from and against any and all claims, demands, actions, suits, proceedings, liabilities, losses, damages, costs, and expenses (including but not limited to reasonable legal fees, court costs, and settlement amounts), whether direct or indirect, arising out of or in connection with:
        </p>
        <ul className="list-disc pl-8 mb-6">
          <li>Any act or omission related to your access to or use of the Website;</li>
          <li>Any breach, alleged breach, or non-compliance with these Terms, including any policies, guidelines, or instructions referenced herein (e.g., Device usage manuals, Privacy Policy);</li>
          <li>Any violation of applicable local, national, or international laws, regulations, or third-party rights, including but not limited to intellectual property rights, privacy, publicity rights, or contractual obligations;</li>
          <li>Any interaction, transaction, or dispute with third-party service providers accessed through the Website.</li>
          <li>Any other act or omission by you that causes harm, loss, or liability to the Indemnified Parties, including but not limited to fraudulent activity, misrepresentation, or damage to the Website's reputation or operations.</li>
        </ul>

        <p className="mb-4">
          Your indemnification obligation extends to: (a) All types of damages, whether compensatory, punitive, exemplary, incidental, consequential, or statutory; (b) Claims brought by any party, including other users, third-party providers, governmental authorities, or private entities; (c) Losses incurred in defending or settling claims, even if such claims are unproven, frivolous, or ultimately dismissed, provided they arise from the circumstances as listed in these Terms.
        </p>

        <p className="mb-8">
          This indemnity applies regardless of whether the claim or loss is caused in whole or in part by your actions, negligence, or willful misconduct, except where liability is solely attributable to the Hospital's gross negligence or willful misconduct, as determined by a court of competent jurisdiction.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Termination</h2>
        <p className="mb-8">
          You agree that Hospital, at its sole discretion, may terminate or suspend your use of the Website at any time and for any or no reason at its sole discretion, even if access and use continue to be allowed to others. Upon such suspension or termination, you must immediately discontinue your use of the Website, and destroy any copies you may have made of any portion of information or content available on the Website. Accessing the website after such termination, or suspension shall constitute an act of trespass. Furthermore, you agree that Hospital shall not be liable to you or any third party for any such termination or suspension of your access to the Website.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Governing Law</h2>
        <p className="mb-4">
          These Terms shall be governed by, and construed in accordance with, the laws of the Republic of India, without regard to its conflict of laws principles. Subject to the paragraph below, the courts located at Bengaluru, Karnataka, India shall have exclusive jurisdiction over any disputes arising out of or in connection with these Terms, the Website.
        </p>

        <p className="mb-4">
          In the event of any dispute, difference, or claim arising out of or in relation to these Terms, including any question regarding its existence, validity, interpretation, performance, or termination, the parties shall first attempt to resolve the dispute amicably through mutual discussions. If the dispute cannot be resolved within thirty (30) days of such attempt, the same shall be referred to and finally resolved by arbitration.
        </p>

        <p className="mb-8">
          The arbitration shall be conducted in accordance with the provisions of the Arbitration and Conciliation Act, 1996, as amended from time to time. The arbitration shall be conducted by a sole arbitrator appointed by mutual consent of the parties. The seat and venue of arbitration shall be Bengaluru, Karnataka, India, and the language of the proceedings shall be English. The arbitral award shall be final and binding on the parties and may be enforced in any court of competent jurisdiction. Nothing in this clause shall prevent either party from seeking urgent interim relief from a court of competent jurisdiction, including injunctions or other equitable remedies.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Grievance Redressal</h2>
        <p className="mb-4">
          If you have any questions, concerns, complaints, or feedback in relation to these Terms, the Website, or any of services, you may contact our designated Grievance Officer using the details provided below:
        </p>
        <div className="pl-8 mb-8">
          <p className="font-semibold">Grievance Officer</p>
          <p>Mr. Himesh Joshi</p>
          <p>Director</p>
          <p>Email: himesh@vikramaura.com</p>
          <p>Working Hours: Monday to Friday 9.30AM to 6.00PM. (Except Public Holidays)</p>
        </div>
        <p className="mb-8">
          We will acknowledge your complaint within three (3) working days of the receipt and will endeavor to resolve it within fifteen (15) days. For urgent or high priority issues, you may also reach us via our designated WhatsApp support channel, details of which will be available on our Website.
        </p>
      </div>
    </div>
  );
};

export default TermsOfService; 